"""Wiki pages: front-matter parsing, serialisation, links, index generation.

Front matter is a deliberately tiny YAML subset (``key: value`` and
``key: [a, b]``) so the project needs no YAML dependency.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field

REQUIRED_FIELDS = ("id", "title", "type", "summary", "sources", "status", "updated")
FIELD_ORDER = REQUIRED_FIELDS + ("raw_path", "raw_sha256")
PAGE_TYPES = ("concept", "source")
STATUSES = ("stable", "needs-review")
ID_RE = re.compile(r"^[a-z0-9][a-z0-9-]{1,63}$")
LINK_RE = re.compile(r"\[\[([^\[\]|#]+)\]\]")


class PageError(ValueError):
    pass


@dataclass
class Page:
    meta: dict
    body: str
    path: str = ""  # workspace-relative, forward slashes

    @property
    def id(self) -> str:
        return str(self.meta.get("id", ""))

    @property
    def type(self) -> str:
        return str(self.meta.get("type", ""))

    @property
    def title(self) -> str:
        return str(self.meta.get("title", ""))

    @property
    def sources(self) -> list:
        value = self.meta.get("sources", [])
        return value if isinstance(value, list) else [value]

    def links(self) -> list[str]:
        """Wikilink targets in the body, in order, without duplicates."""
        seen: dict[str, None] = {}
        for match in LINK_RE.finditer(self.body):
            seen.setdefault(match.group(1).strip(), None)
        return list(seen)


def _parse_value(raw: str):
    raw = raw.strip()
    if raw.startswith("[") and raw.endswith("]"):
        inner = raw[1:-1].strip()
        return [_unquote(v) for v in inner.split(",") if v.strip()] if inner else []
    return _unquote(raw)


def _unquote(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        return value[1:-1]
    return value


def parse_page(text: str, path: str = "") -> Page:
    text = text.replace("\r\n", "\n")
    if not text.startswith("---\n"):
        raise PageError(f"{path or 'page'}: missing front matter (must start with '---')")
    end = text.find("\n---", 4)
    if end == -1:
        raise PageError(f"{path or 'page'}: unterminated front matter")
    meta: dict = {}
    for line in text[4:end].split("\n"):
        if not line.strip():
            continue
        if ":" not in line:
            raise PageError(f"{path or 'page'}: bad front-matter line {line!r}")
        key, value = line.split(":", 1)
        meta[key.strip()] = _parse_value(value)
    body = text[end + 4 :].lstrip("\n")
    return Page(meta=meta, body=body, path=path)


def _format_value(value) -> str:
    if isinstance(value, list):
        return "[" + ", ".join(str(v) for v in value) + "]"
    value = str(value)
    if value != value.strip() or any(c in value for c in ":#[]") or value[:1] in "\"'":
        return '"' + value.replace('"', "'") + '"'
    return value


def render_page(page: Page) -> str:
    keys = [k for k in FIELD_ORDER if k in page.meta]
    keys += [k for k in page.meta if k not in keys]
    lines = ["---"] + [f"{k}: {_format_value(page.meta[k])}" for k in keys] + ["---"]
    return "\n".join(lines) + "\n" + page.body.rstrip("\n") + "\n"


def page_relpath(page_id: str, page_type: str) -> str:
    folder = "sources" if page_type == "source" else "concepts"
    return f"wiki/{folder}/{page_id}.md"


def normalise_title(title: str) -> str:
    return re.sub(r"[^a-z0-9]+", " ", title.lower().replace("sample:", "")).strip()


def render_index(pages: dict[str, Page]) -> str:
    """Deterministic catalogue of every page, grouped by type."""
    out = [
        "# Index",
        "",
        "Generated by the ingest engine from page front matter. Do not edit by hand.",
        "",
    ]
    for page_type, heading in (("concept", "Concepts"), ("source", "Sources")):
        group = sorted((p for p in pages.values() if p.type == page_type), key=lambda p: p.id)
        out.append(f"## {heading} ({len(group)})")
        out.append("")
        for p in group:
            flag = " — **needs review**" if p.meta.get("status") == "needs-review" else ""
            out.append(f"- [[{p.id}]] — {p.meta.get('summary', '')}{flag}")
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"
